/*
 Navicat Premium Data Transfer

 Source Server         : Developpement
 Source Server Type    : MariaDB
 Source Server Version : 100508
 Source Host           : localhost:3306
 Source Schema         : az_world

 Target Server Type    : MariaDB
 Target Server Version : 100508
 File Encoding         : 65001

 Date: 13/06/2021 20:26:13
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for areatrigger_teleport
-- ----------------------------
DROP TABLE IF EXISTS `areatrigger_teleport`;
CREATE TABLE `areatrigger_teleport`  (
  `ID` bigint(20) NOT NULL DEFAULT 0,
  `PortLocID` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `Name` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  FULLTEXT INDEX `name`(`Name`)
) ENGINE = MyISAM CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = 'Trigger System' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of areatrigger_teleport
-- ----------------------------
INSERT INTO `areatrigger_teleport` VALUES (-3, 5293, 'Assault on Violet Hold Entrance');
INSERT INTO `areatrigger_teleport` VALUES (78, 3598, 'Deadmines Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (101, 3599, 'Stormwind Jail Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (109, 3600, 'Stormwind High Prison Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (119, 3601, 'Deadmines Exit Front Target');
INSERT INTO `areatrigger_teleport` VALUES (121, 4292, 'Deadmines Rear Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (145, 3602, 'Shadowfang Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (194, 3603, 'Shadowfang Bridge Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (226, 3604, 'Wailing Caverns Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (228, 3605, 'Wailing Cavern Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (242, 3606, 'Razorfen Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (244, 3607, 'Razorfen Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (257, 3608, 'Blackfathom Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (259, 3609, 'Blackfathom Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (286, 3610, 'Uldaman Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (288, 3611, 'Uldaman Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (322, 3612, 'Gnomeregon Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (324, 3613, 'Gnomeregan Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (442, 3614, 'Razorfen Downs Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (444, 3615, 'Razorfen Downs Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (446, 3616, 'Sunken Temple Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (448, 3617, 'Sunken Temple Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (503, 3618, 'Stormwind Low Prison Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (523, 3619, 'Gnomeregan Entrance 02 Target');
INSERT INTO `areatrigger_teleport` VALUES (525, 3620, 'Gnomeregon Exit 02 Target');
INSERT INTO `areatrigger_teleport` VALUES (527, 3621, 'Darnassus Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (542, 3622, 'Darnassus Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (602, 3623, 'Scarlet Monastery Exit Target 01');
INSERT INTO `areatrigger_teleport` VALUES (604, 3624, 'Scarlet Monastery Exit Target 02');
INSERT INTO `areatrigger_teleport` VALUES (606, 3625, 'Scarlet Monastery Exit Target 03');
INSERT INTO `areatrigger_teleport` VALUES (608, 3626, 'Scarlet Monastery Exit Target 04');
INSERT INTO `areatrigger_teleport` VALUES (610, 3627, 'Scarlet Monastery Entrance Target 02');
INSERT INTO `areatrigger_teleport` VALUES (612, 3628, 'Scarlet Monastery Entrance Target 03');
INSERT INTO `areatrigger_teleport` VALUES (-4, 5446, 'Assault on Violet Hold Exit');
INSERT INTO `areatrigger_teleport` VALUES (882, 3632, 'Uldaman Exit Target Rear');
INSERT INTO `areatrigger_teleport` VALUES (902, 3633, 'Uldaman Entrance Target Rear');
INSERT INTO `areatrigger_teleport` VALUES (922, 3634, 'Zul\'Farrakk Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (924, 3635, 'Zul\'Farrak Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (1064, 3639, 'Onyxia\'s Lair Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (1466, 3643, 'Blackrock Depths Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (1472, 3646, 'Blackrock Depths Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (2166, 3648, 'Ironforge - Tram Exit Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2171, 3649, 'Stormwind - Tram Exit Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2173, 3650, 'Stormwind - Tram Entrance Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2175, 3651, 'Ironforge - Tram Entrance Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2214, 3652, 'Stratholme - Back Entrance Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2216, 3653, 'Stratholme - Front Right Entrance Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2217, 3654, 'Stratholme - Front Left Entrance Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2221, 3655, 'Stratholme - Back Exit Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2226, 3656, 'OrgrimmarInstance Exit Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2230, 3657, 'OrgrimmarInstance Entrance Target 001');
INSERT INTO `areatrigger_teleport` VALUES (4743, 3789, 'Utgarde Pinnacle - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (2530, 3666, 'Orgrimmar - Barracks Exit Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2534, 3667, 'Stormwind - Barracks Exit Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2567, 3671, 'Scholomance 5.0 - Entrance target');
INSERT INTO `areatrigger_teleport` VALUES (2568, 3672, 'Scholomance - Stairs Exit Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2606, 3673, 'Alterac Valley - Horde Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (2608, 3674, 'Alterac Valley - Alliance Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (2848, 3675, 'Onyxia\'s Lair Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (2886, 3676, 'Molten Core Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (2890, 3677, 'Molten Core Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (3126, 3678, 'Maraudon - Purple Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (3131, 3679, 'Maraudon - Orange Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (3133, 3680, 'Maraudon - Orange Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (3134, 3681, 'Maraudon - Purple Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (3183, 3682, 'Dire Maul - East Entrance Target 01');
INSERT INTO `areatrigger_teleport` VALUES (3184, 3683, 'Dire Maul - East Entrance Target 02');
INSERT INTO `areatrigger_teleport` VALUES (3185, 3684, 'Dire Maul - East Entrance Target 03');
INSERT INTO `areatrigger_teleport` VALUES (3186, 3685, 'Dire Maul - West Entrance Target 01');
INSERT INTO `areatrigger_teleport` VALUES (3187, 3686, 'Dire Maul - West Entrance Target 02');
INSERT INTO `areatrigger_teleport` VALUES (3189, 3687, 'Dire Maul - North Entrance Target 02');
INSERT INTO `areatrigger_teleport` VALUES (3190, 3688, 'Dire Maul - West Exit Target 01');
INSERT INTO `areatrigger_teleport` VALUES (3191, 3689, 'Dire Maul - West Exit Target 02');
INSERT INTO `areatrigger_teleport` VALUES (3193, 3690, 'Dire Maul - North Exit Target 02');
INSERT INTO `areatrigger_teleport` VALUES (3194, 3691, 'Dire Maul - East Exit Target 01');
INSERT INTO `areatrigger_teleport` VALUES (3195, 3692, 'Dire Maul - East Exit Target 02');
INSERT INTO `areatrigger_teleport` VALUES (3196, 3693, 'Dire Maul - East Exit Target 03');
INSERT INTO `areatrigger_teleport` VALUES (3197, 3694, 'Dire Maul - East Exit Target 04');
INSERT INTO `areatrigger_teleport` VALUES (3529, 3696, 'Molten Core Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (3726, 3700, 'Blackwing Lair - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (3728, 3701, 'Blackrock Spire Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6321, 3964, 'Badlands 4.x - Cliff Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (3948, 3703, 'Arathi Highlands - Arathi Basin Exit Target - Alliance');
INSERT INTO `areatrigger_teleport` VALUES (3949, 3704, 'Arathi Highlands - Arathi Basin Exit Target - Horde');
INSERT INTO `areatrigger_teleport` VALUES (3528, 3695, 'Molten Core Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4006, 3707, 'Ahn\'Qiraj Ruins - Outbound Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4008, 3708, 'Ahn\'Qiraj Ruins - Inbound Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4010, 3709, 'Ahn\'Qiraj Temple - Inbound Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4012, 3710, 'Ahn\'Qiraj Temple - Outbound Target');
INSERT INTO `areatrigger_teleport` VALUES (4745, 3790, 'Utgarde Keep - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4131, 3712, 'Karazhan - Front Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4145, 3714, 'Hellfire Military - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4147, 3715, 'Hellfire Demon - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4149, 3716, 'Hellfire Raid - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4150, 3717, 'Hellfire Ramparts - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4151, 3718, 'Hellfire Military - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4152, 3719, 'Hellfire Demon - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4153, 3720, 'Hellfire Raid - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4297, 3725, 'Hellfire Ramparts - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4311, 3727, 'CoT - Hyjal - Human Base - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4312, 3728, 'CoT - Hyjal - Orc Base - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4313, 3729, 'CoT - Hyjal - Night Elf Base - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4319, 3730, 'CoT - Hyjal - Entrance - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4320, 3731, 'CoT - Black Morass - Entrance - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4321, 3732, 'CoT - Hillsbrad - Entrance - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4322, 3733, 'CoT - Black Morass - Exit - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4323, 3734, 'CoT - Hyjal - Exit - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4324, 3735, 'CoT - Hillsbrad - Exit - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (1468, 4501, 'Upper Blackrock Spire Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4363, 3738, 'Coilfang Marsh - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4364, 3739, 'Coilfang Pumping - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4365, 3740, 'Coilfang Draenei - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4366, 3741, 'Coilfang Pumping - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4367, 3742, 'Coilfang Marsh - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4379, 3743, 'Coilfang Draenei - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4386, 3744, 'Eastern Plaguelands - From Ghostlands Target');
INSERT INTO `areatrigger_teleport` VALUES (4397, 3745, 'Auchindoun Shadow - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4399, 3746, 'Auchindoun Arakkoa - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4401, 3747, 'Auchindoun Etherial - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4403, 3748, 'Auchindoun Draenei - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4404, 3749, 'Auchindoun Draenei - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4405, 3750, 'Auchindoun Etherial - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4406, 3751, 'Auchindoun Arakkoa - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4407, 3752, 'Auchindoun Shadow - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4409, 3753, 'Ghostlands - EPL Return Target');
INSERT INTO `areatrigger_teleport` VALUES (4416, 3754, 'Coilfang Raid - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4436, 3756, 'Karazhan - Front Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4455, 3761, 'Tempest Keep - Arcane Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4457, 3762, 'Tempest Keep - Raid Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4459, 3763, 'Tempest Keep - Atrium Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4461, 3764, 'Tempest Keep - Factory Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4467, 3765, 'Tempest Keep - Atrium Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4468, 3766, 'Tempest Keep - Arcane Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4469, 3767, 'Tempest Keep - Factory Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4470, 3768, 'Tempest Keep - Raid Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4487, 3770, 'CoT - Hyjal - Exit - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (4534, 3774, 'Gruul\'s Lair - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4535, 3775, 'Gruul\'s Lair - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4598, 3780, 'Black Temple - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4619, 3783, 'Black Temple - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4418, 3755, 'Coilfang Raid - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4738, 3786, 'Zul\'Aman - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4739, 3787, 'Zul\'Aman - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (943, 3636, 'Thousand Needles - Test of Faith (Target)');
INSERT INTO `areatrigger_teleport` VALUES (4135, 3713, 'Karazhan - Upper Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4885, 3793, 'Magisters\' Terrace - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4887, 3794, 'Magisters\' Terrace - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4889, 3795, 'Sunwell Raid - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4891, 3796, 'Sunwell Raid - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4747, 3791, 'Utgarde Pinnacle - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4741, 3788, 'Utgarde Keep - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4983, 3820, 'The Nexus - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4981, 3819, 'The Nexus - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5246, 3876, 'Nexus 80 - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5191, 3857, 'Naxxramas - Entrance Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5192, 3858, 'Naxxramas - Entrance Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5193, 3859, 'Naxxramas - Entrance Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5194, 3860, 'Naxxramas - Entrance Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5196, 3861, 'Naxxramas - Exit Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5197, 3862, 'Naxxramas - Exit Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5198, 3863, 'Naxxramas - Exit Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5199, 3864, 'Naxxramas - Exit Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5150, 3853, 'CoT Stratholme - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5181, 3852, 'CoT Stratholme - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5209, 3867, 'Violet Hold - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5211, 3868, 'Violet Hold - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5206, 3866, 'Gundrak - Entrace Target B (Snake)');
INSERT INTO `areatrigger_teleport` VALUES (5205, 3865, 'Gundrak - Entrace Target A (Mammoth)');
INSERT INTO `areatrigger_teleport` VALUES (5277, 3881, 'Gundrak - Exit Target B (Snake)');
INSERT INTO `areatrigger_teleport` VALUES (5231, 3871, 'Gundrak - Exit Target A (Mammoth)');
INSERT INTO `areatrigger_teleport` VALUES (5093, 3836, 'Ulduar 80 - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5091, 3835, 'Ulduar 80 - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5010, 3825, 'Halls of Stone - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5012, 3826, 'Halls of Stone - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5117, 3839, 'Azjol-Nerub Front Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5115, 3838, 'Azjol-Nerub Front Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5113, 3837, 'Azjol-Nerub Back Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5215, 3870, 'Lower City - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5213, 3869, 'Lower City - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5243, 3875, 'CoA Black - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5241, 3874, 'CoA Black - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4998, 3821, 'Drak\'Tharon - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5000, 3822, 'Drak\'Tharon - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5290, 3882, 'Eye of Eternity - Port In Loc');
INSERT INTO `areatrigger_teleport` VALUES (4520, 3771, 'Karazhan - Upper Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5379, 3903, 'Ulduar Raid - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5381, 3904, 'Ulduar Raid - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5262, 3879, 'Wintergrasp Raid - Teleport Target - Exit');
INSERT INTO `areatrigger_teleport` VALUES (5258, 3878, 'Wintergrasp Raid - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5508, 3916, 'Argent Raid - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5503, 3914, 'Argent Raid - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5505, 3915, 'Argent Dungeon - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5510, 3917, 'Argent Dungeon - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5670, 3929, 'Icecrown Raid - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5668, 3928, 'Icecrown Raid - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5635, 3920, 'Icecrown Dungeon - Forge of Souls - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5636, 3921, 'Icecrown Dungeon - Halls of Reflection - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5637, 3922, 'Icecrown Dungeon - Pit of Saron - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5642, 3923, 'Icecrown Dungeon - Forge of Souls - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5643, 3924, 'Icecrown Dungeon - Pit of Saron - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5646, 3925, 'Icecrown Dungeon - Halls of Reflection - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5683, 3932, 'Icecrown Dungeon - Halls of Reflection - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5688, 3933, 'Icecrown Dungeon - Pit of Saron - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5869, 3940, 'Ruby Sanctum - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (5872, 3941, 'Ruby Sanctum - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5276, 3880, 'Gundrak - Exit Target A (Mammoth)');
INSERT INTO `areatrigger_teleport` VALUES (5233, 3872, 'Gundrak - Exit Target B (Snake)');
INSERT INTO `areatrigger_teleport` VALUES (4612, 3781, 'Tempest Keep - Atrium Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (4614, 3782, 'Tempest Keep - Factory Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6011, 3953, 'Blackrock Caverns - Exit Target (in Eastern Kingdoms)');
INSERT INTO `areatrigger_teleport` VALUES (6108, 3955, 'Blackrock Caverns - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (6177, 3956, 'Grim Batol Dungeon - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6179, 3957, 'Grim Batol Dungeon - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (6194, 3958, 'Deepholm - Stonecore Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6196, 3959, 'Stonecore - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (6197, 3954, 'Vashj\'ir - Throne of Tides Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6201, 3961, 'Throne of Tides - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (6485, 3970, 'Halls of Origination - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (6487, 3971, 'Halls of Origination - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6610, 3975, 'The Vortex Pinnacle - Exit Target (in Kalimdor)');
INSERT INTO `areatrigger_teleport` VALUES (6612, 3976, 'The Vortex Pinnacle - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (6620, 3978, 'Lost City of Tol\'vir - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (6488, 3972, 'Lost City of the Tol\'vir - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6341, 3966, 'Twilight Bastion - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6354, 3967, 'Twilight Bastion - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (6580, 3973, 'Blackwing Descent - Exit Target (in Eastern Kingdoms)');
INSERT INTO `areatrigger_teleport` VALUES (6581, 3974, 'Blackwing Descent - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (6618, 3977, 'Baradin Hold - Exit Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (6664, 3989, 'Baradin Hold - Entrance Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (6672, 3990, 'Skywall Raid - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (6673, 3991, 'Uldum - Skywall Raid Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6864, 3998, 'Firelands - Entrance Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (6866, 3999, 'Firelands - Exit Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (7151, 4003, 'CoT 4.3 - Well of Eternity - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (7161, 4007, 'CoT 4.3 - Well of Eternity - Exit Target (In Kalimdor)');
INSERT INTO `areatrigger_teleport` VALUES (7152, 4004, 'CoT 4.3 - End Time - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (7162, 4008, 'CoT 4.3 - End Time - Exit Target (In Kalimdor)');
INSERT INTO `areatrigger_teleport` VALUES (7154, 4005, 'CoT 4.3 - Hour of Twilight - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (7163, 4009, 'CoT 4.3 - Hour of Twilight - Exit Target (In Kalimdor)');
INSERT INTO `areatrigger_teleport` VALUES (7155, 4006, 'CoT 4.3 - Dragon Soul - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (7164, 4010, 'CoT 4.3 - Dragon Soul - Exit Target (In Kalimdor)');
INSERT INTO `areatrigger_teleport` VALUES (6775, 3996, 'Zul\'Gurub 4.1 - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (6769, 3995, 'Zul\'Gurub 4.1 - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6322, 3965, 'Badlands 4.x - Dock Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (6210, 3962, 'Stratholme - Front Right Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6211, 3963, 'Stratholme - Front Left Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (2406, 3658, 'Shadowfang - South Fall Target');
INSERT INTO `areatrigger_teleport` VALUES (2407, 3659, 'Shadowfang - South Fall Target');
INSERT INTO `areatrigger_teleport` VALUES (2408, 3660, 'Shadowfang Front Fall Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (2409, 3661, 'Shadowfang Front Fall Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (2410, 3662, 'Shadowfang - North Fall Target');
INSERT INTO `areatrigger_teleport` VALUES (2411, 3663, 'Shadowfang - North Fall Target');
INSERT INTO `areatrigger_teleport` VALUES (4233, 3723, 'Eversong Woods - Duskwither UP Target');
INSERT INTO `areatrigger_teleport` VALUES (4267, 3724, 'Eversong Woods - Duskwither DOWN Target');
INSERT INTO `areatrigger_teleport` VALUES (4304, 3726, 'Hellfire Ramparts - Omor Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5148, 3854, 'CoT Stratholme - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5893, 3942, 'Hyjal - Teleport from Seat of the Prophets');
INSERT INTO `areatrigger_teleport` VALUES (5895, 3943, 'Hyjal - Teleport From Sulfuron Spire');
INSERT INTO `areatrigger_teleport` VALUES (5926, 3950, 'The Lost Isles - Volcanoth\'s Lair - Teleport Target - Phase 8+');
INSERT INTO `areatrigger_teleport` VALUES (6073, 3960, 'Vashj\'ir - Throne of Tides Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (-26, 5104, 'Vault of the Warden Exit');
INSERT INTO `areatrigger_teleport` VALUES (-25, 5105, 'Vault of the Warden Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-24, 5472, 'The Arcway Exit');
INSERT INTO `areatrigger_teleport` VALUES (-23, 5194, 'The Arcway Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-21, 5784, 'Return to Karazhan Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-20, 5103, 'Neltharion\'s Lair Exit');
INSERT INTO `areatrigger_teleport` VALUES (-19, 5355, 'Neltharion\'s Lair Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-18, 5123, 'Maw of Souls Exit');
INSERT INTO `areatrigger_teleport` VALUES (-17, 5102, 'Maw of Souls Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-16, 5099, 'Hall of Valors Exit');
INSERT INTO `areatrigger_teleport` VALUES (-15, 5098, 'Hall of Valors Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-10, 5607, 'Court of Stars Exit');
INSERT INTO `areatrigger_teleport` VALUES (-9, 5432, 'Court of Stars Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-8, 5892, 'Cathedral of Eternal Night Exit');
INSERT INTO `areatrigger_teleport` VALUES (-7, 5891, 'Cathedral of Eternal Night Entrance');
INSERT INTO `areatrigger_teleport` VALUES (45, 4078, 'Scarlet Monastery 5.0 Entrance');
INSERT INTO `areatrigger_teleport` VALUES (614, 4077, 'Scarlet Halls 5.0 Entrance');
INSERT INTO `areatrigger_teleport` VALUES (10157, 4698, 'Skyreach Entrance');
INSERT INTO `areatrigger_teleport` VALUES (5326, 3889, 'Arena - Dalaran Arena - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5328, 3890, 'Arena - Dalaran Arena - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5329, 3891, 'Arena - Dalaran Arena - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5330, 3892, 'Arena - Dalaran Arena - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5331, 3893, 'Arena - Dalaran Arena - Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (5447, 3906, 'Arena - Orgrimmar - Teleport Target 3');
INSERT INTO `areatrigger_teleport` VALUES (5127, 3840, 'Ebon Hold (E.K.) Top Return Target');
INSERT INTO `areatrigger_teleport` VALUES (5128, 3841, 'Ebon Hold (E.K.) Top West Target');
INSERT INTO `areatrigger_teleport` VALUES (5129, 3842, 'Ebon Hold (E.K.) Top Return Target');
INSERT INTO `areatrigger_teleport` VALUES (5130, 3843, 'Ebon Hold (E.K.) Top South Target');
INSERT INTO `areatrigger_teleport` VALUES (5131, 3844, 'Ebon Hold (E.K.) Top Return Target');
INSERT INTO `areatrigger_teleport` VALUES (5132, 3845, 'Ebon Hold (E.K.) Top North Target');
INSERT INTO `areatrigger_teleport` VALUES (5133, 3846, 'Ebon Hold (E.K.) Top Return Target');
INSERT INTO `areatrigger_teleport` VALUES (5134, 3847, 'Ebon Hold (E.K.) Top East Target');
INSERT INTO `areatrigger_teleport` VALUES (5135, 3848, 'Ebon Hold (E.K.) Middle -> Bottom Target');
INSERT INTO `areatrigger_teleport` VALUES (5136, 3849, 'Ebon Hold (E.K.) Middle -> Bottom Target');
INSERT INTO `areatrigger_teleport` VALUES (5137, 3850, 'Ebon Hold (E.K.) Bottom -> Middle Target');
INSERT INTO `areatrigger_teleport` VALUES (5138, 3851, 'Ebon Hold (E.K.) Bottom -> Ground Target');
INSERT INTO `areatrigger_teleport` VALUES (2547, 3668, 'Scholomance - Exit Porch Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2548, 3669, 'Scholomance - Exit Porch Target 001');
INSERT INTO `areatrigger_teleport` VALUES (2549, 3670, 'Scholomance - Exit Porch Target 001');
INSERT INTO `areatrigger_teleport` VALUES (5235, 3873, 'Azjol-Nerub Back Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5740, 3937, 'Icecrown Dungeon - Halls of Reflection - Player Bounce Target');
INSERT INTO `areatrigger_teleport` VALUES (8134, 4265, 'Mogu\'shan Palace - Entrance Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (7705, 4049, 'Stormstout Brewery - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (7694, 4026, 'Shadowpan Hideout - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (7726, 4053, 'Gate of the Setting Sun - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (8315, 4353, 'Mantid Siege - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (7854, 4024, 'Jade Temple - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (8135, 4266, 'Mogu\'shan Palace - Exit Teleport Target');
INSERT INTO `areatrigger_teleport` VALUES (7755, 4064, 'Stormstout Brewery - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (7699, 4025, 'Shadowpan Hideout - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (7725, 4054, 'Gate of the Setting Sun - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (8312, 4352, 'Mantid Siege - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (7687, 4023, 'Jade Temple - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (5530, 3918, 'Isle of Conquest - Lighthouse Target');
INSERT INTO `areatrigger_teleport` VALUES (7838, 4094, 'Mogu\'shan Vaults - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (7999, 4139, 'Ring of Valor - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (8001, 4140, 'Ring of Valor - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (8314, 4350, 'Heart of Fear - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (9245, 4572, 'Garrosh Raid - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (9302, 4613, 'Gold Rush BG - Pandaren Mine Catch');
INSERT INTO `areatrigger_teleport` VALUES (9303, 4614, 'Gold Rush BG - Goblin Mine Catch');
INSERT INTO `areatrigger_teleport` VALUES (9681, 4661, 'Bloodmaul Slave Mines - Entrance');
INSERT INTO `areatrigger_teleport` VALUES (9680, 4662, 'Bloodmaul Slave Mines - Exit');
INSERT INTO `areatrigger_teleport` VALUES (8027, 4144, 'Terrace of Endless Spring - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (9964, 4683, 'Auchindoun Dungeon 6.0 - Entrance');
INSERT INTO `areatrigger_teleport` VALUES (9965, 4722, 'Auchindoun Dungeon 6.0 - Exit');
INSERT INTO `areatrigger_teleport` VALUES (10022, 4774, 'Shadowmoon Dungeon - Exit Target (Outside)');
INSERT INTO `areatrigger_teleport` VALUES (10023, 4713, 'Shadowmoon Dungeon - Entrance Target (Inside)');
INSERT INTO `areatrigger_teleport` VALUES (10097, 4823, 'Iron Docks - Exit Target (Outside)');
INSERT INTO `areatrigger_teleport` VALUES (10098, 4680, 'Iron Docks - Entrance Target (Inside)');
INSERT INTO `areatrigger_teleport` VALUES (10104, 4831, 'Blackrock Train Depot - Exit Target - KJD');
INSERT INTO `areatrigger_teleport` VALUES (10124, 3644, 'Lower Blackrock Spire Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (10205, 3645, 'Blackrock Spire Exit Target (New)');
INSERT INTO `areatrigger_teleport` VALUES (10232, 4831, 'Blackrock Train Depot - Exit Target - KJD');
INSERT INTO `areatrigger_teleport` VALUES (10237, 4712, 'Blackrock Train Depot - Entrance Target - KJD');
INSERT INTO `areatrigger_teleport` VALUES (10241, 4778, 'Foundry Raid - Graveyard - Entrance');
INSERT INTO `areatrigger_teleport` VALUES (10242, 4842, 'Gorgrond - Outside Foundry');
INSERT INTO `areatrigger_teleport` VALUES (10244, 4856, 'Overgrown Outpost - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (10272, 4779, 'Highmaul Raid - Instance Entrance');
INSERT INTO `areatrigger_teleport` VALUES (10273, 4920, 'Lower Blackrock Spire - Exit Teleport');
INSERT INTO `areatrigger_teleport` VALUES (2068, 3647, 'Blackrock Spire - Target - Shaft');
INSERT INTO `areatrigger_teleport` VALUES (3606, 3697, 'Molten Core Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (4901, 3797, 'Clayton Teleporter');
INSERT INTO `areatrigger_teleport` VALUES (4909, 3798, 'TEST - CSteele Teleporter Target');
INSERT INTO `areatrigger_teleport` VALUES (4953, 3818, 'Scott Test Target');
INSERT INTO `areatrigger_teleport` VALUES (5254, 3877, 'Teleport to Reliquary of Agony (Target)');
INSERT INTO `areatrigger_teleport` VALUES (5493, 3912, 'Mini House Target');
INSERT INTO `areatrigger_teleport` VALUES (5495, 3913, 'Mega House Target');
INSERT INTO `areatrigger_teleport` VALUES (-43, 3828, 'DK begin Acherus to lower');
INSERT INTO `areatrigger_teleport` VALUES (-44, 3827, 'DK begin Acherus to upper');
INSERT INTO `areatrigger_teleport` VALUES (-11, 5334, 'Darkheart Thicket entrance');
INSERT INTO `areatrigger_teleport` VALUES (-12, 5343, 'Darkheart Thicket exit');
INSERT INTO `areatrigger_teleport` VALUES (-13, 5100, 'Eye of Azshara entrance');
INSERT INTO `areatrigger_teleport` VALUES (-14, 5114, 'Eye of Azshara exit');
INSERT INTO `areatrigger_teleport` VALUES (-34, 5889, 'Tomb of Sargeras entrance');
INSERT INTO `areatrigger_teleport` VALUES (-35, 5890, 'Tomb of Sargeras exit');
INSERT INTO `areatrigger_teleport` VALUES (-5, 5352, 'BlackRook Hold entrance');
INSERT INTO `areatrigger_teleport` VALUES (-6, 5353, 'BlackRook Hold exit');
INSERT INTO `areatrigger_teleport` VALUES (-27, 5533, 'Emerald Nightmare Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-28, 5687, 'Emerald Nightmare Exit');
INSERT INTO `areatrigger_teleport` VALUES (-29, 5775, 'Trial of Valors Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-30, 5779, 'Trial of Valors Exit');
INSERT INTO `areatrigger_teleport` VALUES (-31, 5338, 'The Nighthold Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-32, 5708, 'The Nighthold Exit');
INSERT INTO `areatrigger_teleport` VALUES (-38, 5707, 'Helheim Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-46, 6048, 'Seat of Triumvirate Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-47, 6112, 'Seat of Triumvirate Exit');
INSERT INTO `areatrigger_teleport` VALUES (7839, 4093, 'Mogu\'shan Vaults - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (-51, 6377, 'The Underrot - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (-52, 6378, 'The Underrot - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (-53, 6124, 'Atal dazar - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (-54, 6123, 'Atal dazar - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (-55, 6526, 'Freehold - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (-56, 6335, 'Freehold- Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (-57, 6574, 'Shrine of the storm - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (-58, 6524, 'Shrine of the storm- Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (-59, 6423, 'Temple of Sethraliss - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (-60, 6419, 'Temple of Sethraliss - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (-61, 6631, 'Tol Dagor - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (-62, 6383, 'Tol Dagor - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (-63, 6384, 'Waycrest Manor - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (-64, 6523, 'Waycrest Manor - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (-65, 6580, 'The MotherLode Entrance Target Alliance');
INSERT INTO `areatrigger_teleport` VALUES (-66, 6583, 'The MotherLode exit target alliance');
INSERT INTO `areatrigger_teleport` VALUES (-88, 4715, 'Tanaan Jungle Intro - Dark Portal - Graveyard - PRK');
INSERT INTO `areatrigger_teleport` VALUES (-68, 6359, 'The MotherLode Entrance Starting Loc Horde');
INSERT INTO `areatrigger_teleport` VALUES (-69, 7352, 'Dark Portal to Hellfire Peninsula');
INSERT INTO `areatrigger_teleport` VALUES (-70, 7348, 'Dark Portal to Blasted Lands');
INSERT INTO `areatrigger_teleport` VALUES (-71, 7338, 'Alliance Portal Room Interior');
INSERT INTO `areatrigger_teleport` VALUES (-72, 3630, 'Alliance Portal Room');
INSERT INTO `areatrigger_teleport` VALUES (-73, 7295, 'Alliance Portal Room to Shattrath');
INSERT INTO `areatrigger_teleport` VALUES (-74, 7288, 'Alliance Portal Room to Exodar');
INSERT INTO `areatrigger_teleport` VALUES (-75, 7300, 'Alliance Portal Room to A\'shran');
INSERT INTO `areatrigger_teleport` VALUES (-76, 7285, 'Alliance Portal Room to Dalaran');
INSERT INTO `areatrigger_teleport` VALUES (-77, 7263, 'Alliance Portal Room to Pandaria');
INSERT INTO `areatrigger_teleport` VALUES (-78, 7309, 'Alliance Portal Room to Boralus');
INSERT INTO `areatrigger_teleport` VALUES (-79, 7306, 'Alliance Portal Room to Azsuna');
INSERT INTO `areatrigger_teleport` VALUES (-89, 5022, 'Hellfire Raid - Zone IN Location');
INSERT INTO `areatrigger_teleport` VALUES (-90, 5023, 'Hellfire Raid - Zone Out Location');
INSERT INTO `areatrigger_teleport` VALUES (-101, 6552, 'Uldir - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (-99, 1041, 'Hellfire Peninsula, The Dark Portal');
INSERT INTO `areatrigger_teleport` VALUES (-93, 7228, 'Mechagon - Entrance Target from Portal - (MDE)');
INSERT INTO `areatrigger_teleport` VALUES (-67, 6579, 'The MotherLode exit target horde');
INSERT INTO `areatrigger_teleport` VALUES (-100, 5818, '7.1 Karazhan - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (8882, 4485, 'Thunder King Raid - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (8881, 4484, 'Thunder King Raid - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (-102, 6551, 'Uldir - Exit Target');
INSERT INTO `areatrigger_teleport` VALUES (6339, 3671, 'Scholomance - Entrance target (This was old Scholo entrance)');
INSERT INTO `areatrigger_teleport` VALUES (-111, 6552, 'Uldir - Entrance Target');
INSERT INTO `areatrigger_teleport` VALUES (-110, 6161, '7.3 Argus Raid - Entrance');
INSERT INTO `areatrigger_teleport` VALUES (-112, 6551, 'Uldir - Exit Target');

SET FOREIGN_KEY_CHECKS = 1;
