/*
 Navicat Premium Data Transfer

 Source Server         : Developpement
 Source Server Type    : MariaDB
 Source Server Version : 100508
 Source Host           : localhost:3306
 Source Schema         : az_world

 Target Server Type    : MariaDB
 Target Server Version : 100508
 File Encoding         : 65001

 Date: 13/06/2021 20:45:41
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for playerchoice_response
-- ----------------------------
DROP TABLE IF EXISTS `playerchoice_response`;
CREATE TABLE `playerchoice_response`  (
  `ChoiceId` int(11) NOT NULL,
  `ResponseId` int(11) NOT NULL,
  `Index` int(10) UNSIGNED NOT NULL,
  `ChoiceArtFileId` int(11) NOT NULL DEFAULT 0,
  `Flags` int(11) NOT NULL DEFAULT 0,
  `WidgetSetID` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `UiTextureAtlasElementID` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `SoundKitID` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `GroupID` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `Header` varchar(511) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `SubHeader` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ButtonTooltip` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `Answer` varchar(511) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Description` varchar(2047) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Confirmation` varchar(127) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `RewardQuestID` int(10) UNSIGNED NULL DEFAULT NULL,
  `VerifiedBuild` int(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ChoiceId`, `ResponseId`) USING BTREE
) ENGINE = MyISAM CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of playerchoice_response
-- ----------------------------
INSERT INTO `playerchoice_response` VALUES (262, 570, 0, 1389397, 0, 0, 0, 0, 0, 'Stealth', '', '', 'Select', 'Akaari Blood Darkness is an unsurpassed Eredar assassin, a subject of special pride of the Legion. Her daggers can distort space, hiding its owner in the shade.\r\n\r\nWe have intelligence data indicating where it is currently located. It\'s time to strike.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27602);
INSERT INTO `playerchoice_response` VALUES (255, 546, 0, 1274663, 0, 0, 0, 0, 0, 'Havoc', '', '', 'Select', 'These glaives belong to the former demon hunter Varedis Felsoul, who was slain defending the Black Temple many years ago.\n\nThe Burning Legion\'s master, Kil\'Jaeden the Deceiver, raised Varedis in the Twisting Nether and imbued his glaives with a piece of the demon lord\'s chaotic power.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (262, 568, 0, 1389395, 0, 0, 0, 0, 0, 'Liquidation', '', '', 'Select', 'The Assassins of Kings are the daggers of Garona, with which she killed the objectionable Gul\'dan. They poison the victim with poison that leaves no residue, so when the Assassins of Kings decide someone\'s fate, it is impossible to prove.\r\n\r\nThe mental torment forced Garona to hide the daggers, but later she returned behind them to defeat the dangerous servants of the Legion.\r\n\r\nWe have to find her.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27602);
INSERT INTO `playerchoice_response` VALUES (262, 569, 0, 1389396, 0, 0, 0, 0, 0, 'Thug', '', '', 'Select', 'The creepy admiral Eliza is a thunderstorm in the South Seas. Her cursed blades scare many.\r\n\r\nWe learned that her ship anchored off the coast of Azsuna on the Broken Isles. If you hurry, you can get her blades.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27602);
INSERT INTO `playerchoice_response` VALUES (255, 547, 1, 1274663, 0, 0, 0, 0, 0, 'Vengeance', '', '', 'Select', 'The mighty Aldrachi were one of the few to stand against the Burning Legion. It took Sargeras to fell their greatest champion, seizing his warblades in the process.\n\nNow the traitorous Illidari Caria, servant of Kil\'Jaeden, wields the infamous warblades. The more souls she claims, the more powerful she becomes...', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (265, 584, 0, 1274663, 0, 0, 0, 0, 0, 'Arcane', '', '', 'Select', 'Aluneth was most notably wielded for a time by Aegwynn, the only female Guardian of Tirisfal, although stories indicate that it is far older than she.\n\nToward the end of Aegwynn\'s life, she entrusted the staff to the Blue Dragonflight. Deeming the staff too dangerous to use, they locked it away in a secret vault, where it remains still.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (265, 585, 1, 1274663, 0, 0, 0, 0, 0, 'Fire', '', '', 'Select', '\"Flamestrike\" in its native tongue, Felo\'melorn was borne into battle by members of the Sunstrider family as they proved their valor in the War of the Ancients, during the Troll Wars, and against the death knight Arthas Menethil.\n\nUltimately, the sword was lost in the frigid wastes of Northrend.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (265, 586, 2, 1274662, 0, 0, 0, 0, 0, 'Frost', '', '', 'Select', 'This greatstaff was wielded by Alodi, the first Guardian of Tirisfal. He bore the staff into many battles against Legion forces for the century in which he served as Guardian.\n\nShortly after Alodi stepped down as Guardian, he disappeared with the staff. No one knows where Alodi or the staff ended up, except perhaps Alodi himself.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (231, 478, 0, 1274664, 0, 0, 0, 0, 0, 'Havoc', '', '', 'Extermination', 'Continue your mastery of Havoc.\n\nHavoc specialized demon hunters can use Metamorphosis to turn into winged demons. They focus on Melee DPS.\n\nChoosing Havoc grants |cFFFF0000|Hspell:162264|h[Metamorphosis]|h|r as well as |cFFFF0000|Hspell:185164|h[Mastery: Demonic Presence]|h|r.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (231, 479, 1, 1274665, 0, 0, 0, 0, 0, 'Vengeance', '', '', 'Revenge', 'Change to mastery of Vengeance.\n\nVengeance specialized demon hunters can use Metamorphosis to turn into spiked demons. They focus on Tanking.\n\nChoosing Vengeance grants |cFFFF0000|Hspell:187827|h[Metamorphosis]|h|r as well as |cFFFF0000|Hspell:203747|h[Mastery: Fel Blood]|h|r.\n\nYour |cFFFF0000|Hspell:193921|h[Eye Beam]|h|r will change into |cFFFF0000|Hspell:203720|h[Demon Spikes]|h|r.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (234, 486, 0, 1274666, 0, 0, 0, 0, 0, '', '', '', 'Kayn Sunfury', 'Kayn Sunfury is a loyal soldier and one of Lord Illidan Stormrage\'s most trusted lieutenants.\n\nHe believes that cooperation and personal sacrifice are necessary to defeat the Legion.\n\nHonorable and demanding, he follows Illidan\'s ideals to get the job done no matter the cost.\n\n|cFF7a0000 This story choice will not affect your character\'s power.|r', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (234, 487, 1, 1274661, 0, 0, 0, 0, 0, '', '', '', 'Altruis the Sufferer', 'Altruis the Sufferer is a renegade who takes matters into his own hands.\n\nAlthough he and Illidan share the same goals, he often disagrees with Illidan\'s methods.\n\nBelieving Illidan no longer controls his demonic powers, Altruis wants new leadership for the Illidari.\n\n|cFF7a0000 This story choice will not affect your character\'s power.|r', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (245, 525, 0, 1389403, 0, 0, 0, 0, 0, 'Destruction', '', '', 'Select', 'Crafted by hundreds of eredar warlocks and the Dark Titan himself, it was used for terrible acts of destruction. Capable of tearing gaps in reality to other worlds, it was the key to the invasion of Azeroth.\n\nLater used by Nerzhul, he thoughtlessly unleashed its power on Draenor, causing its near destruction. Thought to be long lost, it has returned to the hands of the Legion.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (245, 524, 1, 1389402, 0, 0, 0, 0, 0, 'Demonology', '', '', 'Select', 'The sorcerer Thal\'kiel was one of the first Eredar who learned the techniques of summoning and controlling demons.\nAfter his defeat, his skull was put on display as an example of the dangers of the dark arts.\nThe lesson went unheeded.\n\nAfter the Eredar\'s fall, the skull was taken by the generals of the Burning Legion to enhance their control of their armies.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (247, 531, 0, 1390104, 0, 0, 0, 0, 0, 'Guardian', '', '', 'Select', 'The mighty bear god, Ursoc, died during the War of the Ancients defending Azeroth from the Burning Legion.\n\nThe last remnants of his physical form, his claws, were placed within the Emerald Dream for safekeeping. There, his spirit still guards over them.\n\nIf you can obtain the claws they would be a valuable asset in our battles against the Legion.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (247, 530, 1, 1390103, 0, 0, 0, 0, 0, 'Feral', '', '', 'Select', 'Ashamane, an ancient and powerful nightsaber, fought in the War of the Ancients and fell ages ago deep in the forests of Val\'Sharah.\n\nA group of druids called the Ashen honor her memory and are the guardians of the shrine that houses her fangs. \n\nWe will need to persuade them to allow their precious artifact to be used in combat, but the fangs would be a powerful weapon against the Legion.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (247, 529, 2, 1390102, 0, 0, 0, 0, 0, 'Balance', '', '', 'Select', 'Held for safe keeping by Tyrande, the High Priestess of Elune, the Scythe of Elune carries a long and unsettling history for druids.\n\nTied to the origin of the worgen on Azeroth, the scythe is said to possess untold lunar power for the druid with balance enough to keep control.\n\nWe need only to convince Tyrande\'s people that you are worthy to keep it safe in the battles to come.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (236, 491, 0, 1274663, 0, 0, 0, 0, 0, 'Arms', '', '', 'Select', 'The first king of the humans, Thoradin, was a mighty ruler and a mighty warrior. He carried with him a greatsword forged by vrykul, empowered by elves, and bloodied on the fields of countless battles.\n\nStrom\'kar, ender of wars, was lost with Thoradin. One strong enough to recover the sword would bring to bear a blade unlike any seen ages since.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (236, 492, 1, 1274663, 0, 0, 0, 0, 0, 'Protection', '', '', 'Select', 'An ancient vrykul king crafted a stolen scale of Neltharion, the Earth-Warder into a bulwark of immense power. This great shield now lies by his side, deep in a nearly forgotten tomb.\n\nReclaim this shield and you will reap not only an impenetrable guard, but also a glimpse of the mighty fiery powers of the dragon aspect himself.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (236, 493, 2, 1274663, 0, 0, 0, 0, 0, 'Fury', '', '', 'Select', 'The warswords of my very own Valarjar, my greatest champion, stolen from me by the curr, Helya. She and her fool servant make a mockery of their prowess by stealing the souls of great heroes before they can ascend to the Halls of Valor.\n\nMighty weapons that would turn you into a living storm of steel and fire. They would make a worthy choice.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (235, 488, 0, 1271766, 0, 0, 0, 0, 0, 'Holy', '', '', 'Select', 'A secret order of paladins has been watching over the resting place of the great titan watcher Tyr for hundreds of years. Histories tell that his powerful warhammer as buried there with him.\n\nRecent events have threatened the safety of their secret charge, and they have appealed for help from paladins across Azeroth.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (235, 489, 1, 1271767, 0, 0, 0, 0, 0, 'Protection', '', '', 'Select', 'An ancient vrykul saga speaks of a shield crafted by Tyr himself. During the Winterskorn War it was used to expose Loken\'s lies to the vrykul and convert many to Tyr\'s cause.\n\nThe shield final resting place of the shield was lost to time, but rumors point to one who might know the final chapters of its story.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (235, 490, 2, 1271768, 0, 0, 0, 0, 0, 'Retribution', '', '', 'Select', 'During our failed assault on the Broken Shore, Highlord Tirion Fordring was lost, and with him our greatest weapon against the Legion... the Ashbringer.\n\nWe need to return to the Broken Shore and recover Tirion and the Ashbringer at all costs.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (240, 505, 0, 1390108, 0, 0, 0, 0, 0, 'Survival', '', '', 'Select', 'The Highmountain tribe lost their greatest weapon, the ancient spear of Huln Highmountain, long ago to a magically corrupted monstrosity.\n\nThey ask you to travel to Stormheim, kill their nemesis, and reclaim the spear for the fight against the Legion.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (240, 506, 1, 1390107, 0, 0, 0, 0, 0, 'Marksmanship', '', '', 'Select', 'Many years ago, the ranger Alleria Windrunner wielded her family bow, Thas\'dorah, to batle the Legion. Her current whereabouts are unknown.\n\nIf Alleria could be located, her weapon would become a valuable asset in the war against the demons.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (266, 587, 0, 1389399, 0, 0, 0, 0, 0, 'Enhancement', '', '', 'Select', 'The Doomhammer has fallen into the Maelstrom. It would be wise to keep it from falling into the wrong hands.\n\nTravel with Thrall into Deepholm to pursue the missing artifact. Beware - the demon Geth\'xun also plummeted into the Maelstrom and may still be alive.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (266, 588, 1, 1389398, 0, 0, 0, 0, 0, 'Elemental', '', '', 'Select', 'The gladiator Rehgar knows of a powerful weapon that may aid us against the Legion.\n\nAfter the Pandaren Campaign, the weapons of the storm god Ra-Den were discovered beneath the Throne of Thunder. They were placed in the care of the White Tiger, who will give them only to one who is worthy. Rehgar will help you prove your worth!', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (266, 589, 2, 1389400, 0, 0, 0, 0, 0, 'Restoration', '', '', 'Select', 'It is said that Queen Azshara wielded a scepter that had command over the sea and the waters of life.\n\nErunak has long sought the location of this artifact, and one of his shaman was close to finding it when she disappeared. Has she found it? Could the legends be true? What could such an artifact do in the hands of a talented shaman?', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (56, 129, 0, 1041263, 0, 0, 0, 0, 0, '', '', '', 'Lowland sawmill', 'The lowland sawmill provides resources daily and reduces the cost of other garrison buildings and specializations.\r\n\r\nAs soon as the sawmill is completed, you will see the ability | cFFFF0000 | Hspell: 164050 | h [Call mechanical shredder-5000] | h | r within Gorgronda.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (56, 130, 1, 1041769, 0, 0, 0, 0, 0, '', '', '', 'Savage Fight Club', 'The Savage Fight Club will provide training tasks to improve teammates.\r\n\r\nAs soon as the fight club is completed, you will have the ability | cFFFF0000 | Hspell: 164012 | h [Hero\'s Honor] | h | r within Gorgrond.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (52, 121, 0, 986495, 0, 0, 0, 0, 0, '', '', '', 'Armory Vol\'jina', 'The Vol\'jin Armory provides high-quality weapons and armor for your soldiers.\r\n\r\nAs soon as the armory is completed, you will have the ability | cFFFF0000 | Hspell: 162075 | h [Artillery strike] | h | r within Talador.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (52, 122, 1, 986497, 0, 0, 0, 0, 0, '', '', '', 'Magic sanctuary', 'The magic sanctuary will turn part of your troops into powerful spellcasters.\r\n\r\nAs soon as the sanctuary is completed, you will have the ability | cFFFF0000 | Hspell: 161767 | h [Security sphere] | h | r within Talador.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (55, 127, 0, 1041262, 0, 0, 0, 0, 0, '', '', '', 'Highpass Logging Camp', 'The Highpass Logging Camp will allow for operations in the jungle overgrowth of southern Gorgrond.\n\nOnce fully operational, the Highpass Logging Camp grants the use of |cFFFF0000|Hspell:164050|h[Summon Mechashredder 5000]|h|r within Gorgrond.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (55, 128, 1, 1041768, 0, 0, 0, 0, 0, '', '', '', 'Highpass Sparring Ring', 'The Highpass Sparring Ring will allow for operations in the brutal wastelands of northern Gorgrond.\n\nOnce fully operational, the  Highpass Sparring Ring grants the use of |cFFFF0000|Hspell:164012|h[Champion\'s Honor]|h|r within Gorgrond.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (51, 119, 0, 986494, 0, 0, 0, 0, 0, '', '', '', 'Wrynn Artillery Tower', 'The Wrynn Artillery Tower will provide higher quality weapons and armor for your troops.\n\nOnce fully operational, the Wrynn Artillery Tower grants the use of |cFFFF0000|Hspell:162075|h[Artillery Strike]|h|r within Talador.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (51, 120, 1, 986496, 0, 0, 0, 0, 0, '', '', '', 'Arcane Sanctum', 'The Arcane Sanctum will transform some of your forces into powerful spellcasters.\n\nOnce fully operational, it grants the use of |cFFFF0000|Hspell:161767|h[Guardian Orb]|h|r within Talador.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (58, 133, 0, 1041764, 0, 0, 0, 0, 0, '', '', '', 'Stoktron Brewery', 'The Stoktron Brewery will provide housing for additional troops and boosts the morale of your forces.\n\nOnce fully operational, the Stoktron Brewery grants the use of |cFFFF0000|Hspell:168487|h[Home Away from Home]|h|r within Spires of Arak.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (58, 134, 1, 1041766, 0, 0, 0, 0, 0, '', '', '', 'Smuggler\'s Den', 'The Smuggler\'s Den will open up trade routes with other forces, granting access to rare supplies and materials.\n\nOnce fully operational, the Smuggler\'s Den grants the use of |cFFFF0000|Hspell:170108|h[Smuggling Run!]|h|r within Spires of Arak.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (65, 147, 0, 1042055, 0, 0, 0, 0, 0, '', '', '', 'Magnarok', 'Colossal magnaron, gronn, and other stone monstrosities have been threatening our outposts in the west. Most seem to originate from Magnarok in Frostfire Ridge.\n\nIf we strike at them at their home, we should be able to force them back. It\'s risky, but it may be our best move. While you\'re there, see if you can recover any of our supplies.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (65, 148, 1, 1042005, 0, 0, 0, 0, 0, '', '', '', 'The Pit (Group)', 'The Blackrock forces based out of the Pit in Gorgrond make up the bulk of the Iron Horde army. If we crush them on their home soil, the rest of the Iron Horde will have little hope of standing against us.\n\nIf you choose the battle, bring friends. The Blackrock won\'t be defeated easily.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (53, 123, 0, 1011903, 0, 0, 0, 0, 0, '', '', '', 'Stall rangari', 'Rangari stalls will provide improved riding tanks for your soldiers.\r\n\r\nAs soon as the stalls are completed, you will have the ability | cFFFF0000 | Hspell: 165803 | h [Telaar Talbuk] | h | r within Nagrand.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (53, 124, 1, 1011905, 0, 0, 0, 0, 0, '', '', '', 'Tank workshop of Telaar', 'The Telaar Tank Shop will provide siege vehicles for your soldiers.\r\n\r\nAs soon as the workshop is completed, you will have the ability | cFFFF0000 | Hspell: 160240 | h [Telaar tank] | h | r within Nagrand.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (116, 249, 0, 1041782, 0, 0, 0, 0, 0, '', '', '', 'Shadowmoon Enclave', 'Remains of the Shadowmoon clan continue their subversive activities in the mountains on the eastern border of Arak Peaks.\r\n\r\nBoudrick Gray is concerned that the enemy has come too close to the garrison, and instructed to deal with this problem as soon as possible.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (116, 250, 1, 1042076, 0, 0, 0, 0, 0, '', '', '', 'Ashran (PvP)', 'While we are fighting in Draenor, the vile Horde is trying to recapture the lands of Ashran from us.\r\n\r\nThe fighting spirit of our troops will rise if you take part in the battle and strike terror into the hearts of enemies.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (120, 257, 0, 1042055, 0, 0, 0, 0, 0, '', '', '', 'Magnarok', 'Huge magnarons, gronns and other stone monsters - all of them threaten our western borders. Most of them seem to be from Magnarok, on the Frostfire Range.\r\n\r\nBy hitting them in their own lair, we will force them to retreat from our lands. This is risky, but we have no better plan. And while you\'re there, look for our supplies.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (120, 258, 1, 1042076, 0, 0, 0, 0, 0, '', '', '', 'Ashran (PvP)', 'While we are fighting in Draenor, the vile Horde is trying to recapture the lands of Ashran from us.\r\n\r\nThe fighting spirit of our troops will rise if you take part in the battle and strike terror into the hearts of enemies.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (109, 235, 0, 1042055, 0, 0, 0, 0, 0, '', '', '', 'Magnarok', 'Huge magnarons, gronns and other stone monsters - all of them threaten our western borders. Most of them seem to be from Magnarok, on the Frostfire Range.\r\n\r\nBy hitting them in their own lair, we will force them to retreat from our lands. This is risky, but we have no better plan. And while you\'re there, look for our supplies.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (109, 236, 1, 1042054, 0, 0, 0, 0, 0, '', '', '', 'Iron Horde Camp', 'Iron Horde fighting vehicles enter the battlefield in dozens, and it is extremely difficult for us to resist them. Apparently, these combat vehicles are being taken from the siege camp of the Iron Horde, which is located in the eastern part of the Icefire Range.\r\n\r\nIf we knock out the Iron Horde from the siege camp and stop the supply of military vehicles, we will turn the tide of the war.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (95, 207, 0, 1042006, 0, 0, 0, 0, 0, '', '', '', 'Thickets of Eternal Blossom', 'Botany and the monster plants they created are slowly getting to our outposts in the north. In place of each dead creature, several new ones immediately appear.\r\n\r\nBoudrick Gray believes that we must deliver a counterattack to the very heart of their possessions and attack the Eternal Flowering Thickets. He hopes that this way we can throw them back into the wilderness of Gorgrond, and then we will have room for maneuver.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (95, 208, 1, 1041981, 0, 0, 0, 0, 0, '', '', '', 'Shattrath', 'Shattrath is under the control of Sargerai troops led by exarch traitor Socrethar.\r\n\r\nSha\'tar defenders are asking for help in fighting the Shadow Council forces in the eastern part of the city.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (72, 161, 0, 1041783, 0, 0, 0, 0, 0, '', '', '', 'Upper Skettis', 'We regularly receive disturbing reports from the south - bird people ambush caravans on major trade routes and burn them.\r\n\r\nThe guards at our outposts are asking to take action and counterattack the main forces of the adherents of Rukhmar in Skettis on the Peaks of Arak.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (72, 162, 1, 1042005, 0, 0, 0, 0, 0, '', '', '', 'Pit (group)', 'The forces of the Blackrock clan, based in the Pit area of ​​Gorgrond, form the backbone of the Iron Horde army. If we smash them in their native land, the remnants of the Iron Horde will no longer be able to withstand us.\r\n\r\nIf you decide on this battle, take reliable comrades with you. It’s definitely not worth counting on an easy victory over the Black Mountain clan.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (99, 215, 0, 1042067, 0, 0, 0, 0, 0, '', '', '', 'Plateau of the Secretary', 'Recent reports indicate increased activity of the Sargerai troops on the Socretar Plateau in the Shadowmoon Valley.\r\n\r\nSocrethar\'s minions present a danger to both the draenei and our garrison. You need to deal with them as soon as possible.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (99, 216, 1, 1041981, 0, 0, 0, 0, 0, '', '', '', 'Shattrath', 'Shattrath is under the control of Sargerai troops led by exarch traitor Socrethar.\r\n\r\nSha\'tar defenders are asking for help in fighting the Shadow Council forces in the eastern part of the city.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (57, 131, 0, 1041765, 0, 0, 0, 0, 0, '', '', '', 'Tavern \"Home\"', 'The Home Hearth Tavern will accommodate more soldiers and raise the morale of your troops.\r\n\r\nAs soon as the tavern is completed, you will have the ability | cFFFF0000 | Hspell: 168499 | h [Home away from home] | h | r within the Peaks of Arak.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (57, 132, 1, 1041767, 0, 0, 0, 0, 0, '', '', '', 'Smugglers\' Lair', 'The lair of smugglers will allow to establish ways of communication with other troops and gain access to rare resources and supplies.\r\n\r\nAs soon as the lair is completed, you will see the ability | cFFFF0000 | Hspell: 170097 | h [Smuggled path!] | H | r within the Peaks of Arak.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (54, 125, 0, 1011904, 0, 0, 0, 0, 0, '', '', '', 'Vorvarskie stall', 'Vor\'var stalls will provide improved mountable Frostwolves for your soldiers.\r\n\r\nAs soon as the stalls are completed, you will have the ability | cFFFF0000 | Hspell: 164222 | h [Northern War Wolf] | h | r within Nagrand.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (54, 126, 1, 1011906, 0, 0, 0, 0, 0, '', '', '', 'Tank workshop of Vor\'var', 'The Vor\'war tank workshop will provide destroyers for your soldiers.\r\n\r\nAs soon as the workshop is completed, you will have the ability | cFFFF0000 | Hspell: 160241 | h [Vor\'var destroyer] | h | r within Nagrand.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (165, 347, 0, 1041776, 0, 0, 0, 0, 0, '', '', '', 'Broken shore', 'Crowds of ogrons attack our positions. No matter how much we kill, new ones appear all the time.\r\n\r\nMost of them seem to come from the Broken Shore, in western Nagrand. If we want to keep the chances of success in future battles, it is necessary to stop the attacks of these ogrons.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (165, 348, 1, 1041980, 0, 0, 0, 0, 0, '', '', '', 'Shattrath (group)', 'Every day, the Sargerai troops in Shattrath are becoming stronger and bolder. They pose a serious threat and can no longer be ignored.\r\n\r\nGather allies if you want to launch an attack on the Sargerais who took refuge in the city.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (154, 325, 0, 1042053, 0, 0, 0, 0, 0, '', '', '', 'Magnarok', 'Huge magnarons, gronns and other stone monsters - all of them threaten our western borders. Most of them seem to be from Magnarok, on the Frostfire Range.\r\n\r\nBy hitting them in their own lair, we will force them to retreat from our lands. This is risky, but we have no better plan. And while you\'re there, look for our supplies.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (154, 326, 1, 1041981, 0, 0, 0, 0, 0, '', '', '', 'Ashran (PvP)', 'While we are fighting on Draenor, the vile Alliance is trying to recapture the lands of Ashran from us.\r\n\r\nThe fighting spirit of our troops will rise if you take part in the battle and strike terror into the hearts of enemies.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (147, 311, 0, 1042066, 0, 0, 0, 0, 0, '', '', '', 'Darktide Nesting Ground', 'During our battles with the Iron Horde, more and more rilaks begin to appear on the battlefield. If you do not deal with them, then we will lose control of all roads and will be forced to retreat to outposts.\r\n\r\nMost likely, these rilaks are sent from the Darktide Nest in the Shadowmoon Valley. If we act quickly, we can solve this problem.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (147, 312, 1, 1041980, 0, 0, 0, 0, 0, '', '', '', 'Shattrath (group)', 'Every day, the Sargerai troops in Shattrath are becoming stronger and bolder. They pose a serious threat and can no longer be ignored.\r\n\r\nGather allies if you want to launch an attack on the Sargerais who took refuge in the city.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (166, 349, 0, 1042053, 0, 0, 0, 0, 0, '', '', '', 'Lands of Stone Fury', 'The Bloodmaul ogres from Frostfire Ridge ambush trade routes across the continent and force captured soldiers to work in their slag mines.\r\n\r\nThe Dark Hunter Rokhan asks for the release of the captured allies held in the main Bloodmaul camp in the Lands of Stone Fury.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (166, 350, 1, 1041980, 0, 0, 0, 0, 0, '', '', '', 'Shattrath (group)', 'Every day, the Sargerai troops in Shattrath are becoming stronger and bolder. They pose a serious threat and can no longer be ignored.\r\n\r\nGather allies if you want to launch an attack on the Sargerais who took refuge in the city.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (140, 297, 0, 1042053, 0, 0, 0, 0, 0, '', '', '', 'Lands of Stone Fury', 'The Bloodmaul ogres from Frostfire Ridge ambush trade routes across the continent and force captured soldiers to work in their slag mines.\r\n\r\nThe Dark Hunter Rokhan asks for the release of the captured allies held in the main Bloodmaul camp in the Lands of Stone Fury.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (140, 298, 1, 1042005, 0, 0, 0, 0, 0, '', '', '', 'Pit (group)', 'The forces of the Blackrock clan, based in the Pit area of ​​Gorgrond, form the backbone of the Iron Horde army. If we smash them in their native land, the remnants of the Iron Horde will no longer be able to withstand us.\r\n\r\nIf you decide on this battle, take reliable comrades with you. It’s definitely not worth counting on an easy victory over the Black Mountain clan.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (141, 299, 0, 1041782, 0, 0, 0, 0, 0, '', '', '', 'Shadowmoon Enclave', 'Remains of the Shadowmoon clan continue their subversive activities in the mountains on the eastern border of Arak Peaks.\r\n\r\nRokhan is concerned that they are too close to the key passes leading to the Shadowmoon Valley, and asks urgently to weaken the enemy.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (141, 300, 1, 1041980, 0, 0, 0, 0, 0, '', '', '', 'Shattrath (group)', 'Every day, the Sargerai troops in Shattrath are becoming stronger and bolder. They pose a serious threat and can no longer be ignored.\r\n\r\nGather allies if you want to launch an attack on the Sargerais who took refuge in the city.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (63, 143, 0, 1042053, 0, 0, 0, 0, 0, '', '', '', 'Lands of Stone Fury', 'The Bloodmaul ogres from Frostfire Ridge ambush trade routes across the continent and force captured soldiers to work in their slag mines.\r\n\r\nThe Dark Hunter Rokhan asks for the release of the captured allies held in the main Bloodmaul camp in the Lands of Stone Fury.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (63, 144, 1, 1041981, 0, 0, 0, 0, 0, '', '', '', 'Shattrath', 'Shattrath is under the control of Sargerai troops led by exarch traitor Socrethar.\r\n\r\nThanks to the help of the Nether demons, the forces of the Shadow Council are strengthening their position in the eastern part of the city. They must be dealt with before they become a threat to us.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (91, 199, 0, 1042066, 0, 0, 0, 0, 0, '', '', '', 'Darktide Nesting Ground', 'During our battles with the Iron Horde, more and more rilaks begin to appear on the battlefield. If you do not deal with them, then we will lose control of all roads and will be forced to retreat to outposts.\r\n\r\nMost likely, these rilaks are sent from the Darktide Nest in the Shadowmoon Valley. If we act quickly, we can solve this problem.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (91, 200, 1, 1041980, 0, 0, 0, 0, 0, '', '', '', 'Shattrath (group)', 'Every day, the Sargerai troops in Shattrath are becoming stronger and bolder. They pose a serious threat and can no longer be ignored.\r\n\r\nGather allies if you want to launch an attack on the Sargerais who took refuge in the city.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (158, 333, 0, 1041783, 0, 0, 0, 0, 0, '', '', '', 'Upper Skettis', 'We regularly receive disturbing reports from the south - bird people ambush caravans on major trade routes and burn them.\r\n\r\nThe guards at our outposts are asking to take action and counterattack the main forces of the adherents of Rukhmar in Skettis on the Peaks of Arak.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (158, 334, 1, 1041981, 0, 0, 0, 0, 0, '', '', '', 'Shattrath', 'The city of Shattrath is under the control of the Sargerai troops commanded by the former exarch, the traitor Socrethar.\r\n\r\nThe forces of the Council of Shadows in the eastern part of the city are strengthening their positions thanks to the support of the demons from the Void, and we must deliver a crushing blow to them until they threaten to disrupt our entire operation.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (152, 321, 0, 1042006, 0, 0, 0, 0, 0, '', '', '', 'Thickets of Eternal Blossom', 'Botany and the monster plants they created are slowly getting to our outposts in the north. In place of each dead creature, several new ones immediately appear.\r\n\r\nRokhan believes that we must deliver a counterattack to the very heart of their possessions and attack the Thickets of Eternal Blossom. He hopes that this way we can throw them back into the wilderness of Gorgrond, and then we will have room for maneuver.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (152, 322, 1, 1042077, 0, 0, 0, 0, 0, '', '', '', 'Ashran (PvP)', 'While we are fighting on Draenor, the vile Alliance is trying to recapture the lands of Ashran from us.\r\n\r\nThe fighting spirit of our troops will rise if you take part in the battle and strike terror into the hearts of enemies.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (135, 287, 0, 1041783, 0, 0, 0, 0, 0, '', '', '', 'Upper Skettis', 'We regularly receive disturbing reports from the south - bird people ambush caravans on major trade routes and burn them.\r\n\r\nThe guards at our outposts are asking to take action and counterattack the main forces of the adherents of Rukhmar in Skettis on the Peaks of Arak.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (135, 288, 1, 1041980, 0, 0, 0, 0, 0, '', '', '', 'Shattrath (group)', 'Every day, the Sargerai troops in Shattrath are becoming stronger and bolder. They pose a serious threat and can no longer be ignored.\r\n\r\nGather allies if you want to launch an attack on the Sargerais who took refuge in the city.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (172, 361, 0, 1042067, 0, 0, 0, 0, 0, '', '', '', 'Plateau of the Secretary', 'Recent reports indicate increased activity of the Sargerai troops on the Socretar Plateau, in the south of the Shadowmoon Valley.\r\n\r\nSocrethar\'s minions are a danger to all Draenor. They must not be allowed to strengthen so far from our positions.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (172, 362, 1, 1042005, 0, 0, 0, 0, 0, '', '', '', 'Pit (group)', 'The forces of the Blackrock clan, based in the Pit area of ​​Gorgrond, form the backbone of the Iron Horde army. If we smash them in their native land, the remnants of the Iron Horde will no longer be able to withstand us.\r\n\r\nIf you decide on this battle, take reliable comrades with you. It’s definitely not worth counting on an easy victory over the Black Mountain clan.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (150, 317, 0, 1041782, 0, 0, 0, 0, 0, '', '', '', 'Shadowmoon Enclave', 'Remains of the Shadowmoon clan continue their subversive activities in the mountains on the eastern border of Arak Peaks.\r\n\r\nRokhan is concerned that they are too close to the key passes leading to the Shadowmoon Valley, and asks urgently to weaken the enemy.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (150, 318, 1, 1042077, 0, 0, 0, 0, 0, '', '', '', 'Ashran (PvP)', 'While we are fighting on Draenor, the vile Alliance is trying to recapture the lands of Ashran from us.\r\n\r\nThe fighting spirit of our troops will rise if you take part in the battle and strike terror into the hearts of enemies.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (161, 339, 0, 1042006, 0, 0, 0, 0, 0, '', '', '', 'Thickets of Eternal Blossom', 'Botany and the monster plants they created are slowly getting to our outposts in the north. In place of each dead creature, several new ones immediately appear.\r\n\r\nRokhan believes that we must deliver a counterattack to the very heart of their possessions and attack the Thickets of Eternal Blossom. He hopes that this way we can throw them back into the wilderness of Gorgrond, and then we will have room for maneuver.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (161, 340, 1, 1042005, 0, 0, 0, 0, 0, '', '', '', 'Pit (group)', 'The forces of the Blackrock clan, based in the Pit area of ​​Gorgrond, form the backbone of the Iron Horde army. If we smash them in their native land, the remnants of the Iron Horde will no longer be able to withstand us.\r\n\r\nIf you decide on this battle, take reliable comrades with you. It’s definitely not worth counting on an easy victory over the Black Mountain clan.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (160, 337, 0, 1041778, 0, 0, 0, 0, 0, '', '', '', 'Mok\'gol Watchtower', 'Songs of War raiders from the Mok\'gol watchtower haunt the entire district. We warn travelers that traveling alone is very dangerous, but not everyone is listening to us.\r\n\r\nIf we attack the Mok\'gol outpost, the War Song clan will go on the defensive, and their raiders will not bother us.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (160, 338, 1, 1041981, 0, 0, 0, 0, 0, '', '', '', 'Shattrath', 'The city of Shattrath is under the control of the Sargerai troops commanded by the former exarch, the traitor Socrethar.\r\n\r\nThe forces of the Council of Shadows in the eastern part of the city are strengthening their positions thanks to the support of the demons from the Void, and we must deliver a crushing blow to them until they threaten to disrupt our entire operation.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (174, 365, 0, 1041778, 0, 0, 0, 0, 0, '', '', '', 'Mok\'gol Watchtower', 'Songs of War raiders from the Mok\'gol watchtower haunt the entire district. We warn travelers that traveling alone is very dangerous, but not everyone is listening to us.\r\n\r\nIf we attack the Mok\'gol outpost, the War Song clan will go on the defensive, and their raiders will not bother us.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (174, 366, 1, 1041980, 0, 0, 0, 0, 0, '', '', '', 'Shattrath (group)', 'Every day, the Sargerai troops in Shattrath are becoming stronger and bolder. They pose a serious threat and can no longer be ignored.\r\n\r\nGather allies if you want to launch an attack on the Sargerais who took refuge in the city.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (169, 355, 0, 1042066, 0, 0, 0, 0, 0, '', '', '', 'Darktide Nesting Ground', 'During our battles with the Iron Horde, more and more rilaks begin to appear on the battlefield. If you do not deal with them, then we will lose control of all roads and will be forced to retreat to outposts.\r\n\r\nMost likely, these rilaks are sent from the Darktide Nest in the Shadowmoon Valley. If we act quickly, we can solve this problem.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (169, 356, 1, 1042005, 0, 0, 0, 0, 0, '', '', '', 'Pit (group)', 'The forces of the Blackrock clan, based in the Pit area of ​​Gorgrond, form the backbone of the Iron Horde army. If we smash them in their native land, the remnants of the Iron Horde will no longer be able to withstand us.\r\n\r\nIf you decide on this battle, take reliable comrades with you. It’s definitely not worth counting on an easy victory over the Black Mountain clan.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (86, 189, 0, 1041782, 0, 0, 0, 0, 0, '', '', '', 'Shadowmoon Enclave', 'Remains of the Shadowmoon clan continue their subversive activities in the mountains on the eastern border of Arak Peaks.\r\n\r\nBoudrick Gray is concerned that the enemy has come too close to the garrison, and instructed to deal with this problem as soon as possible.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (86, 190, 1, 1041980, 0, 0, 0, 0, 0, '', '', '', 'Shattrath (group)', 'Every day, the Sargerai troops in Shattrath are becoming stronger and bolder. They pose a serious threat and can no longer be ignored.\r\n\r\nGather allies if you want to launch an attack on the Sargerais who took refuge in the city.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (151, 319, 0, 1042067, 0, 0, 0, 0, 0, '', '', '', 'Плато Сокретара', 'Recent reports indicate increased activity of the Sargerai troops on the Socretar Plateau, in the south of the Shadowmoon Valley.\r\n\r\nSocrethar\'s minions are a danger to all Draenor. They must not be allowed to strengthen so far from our positions.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (151, 320, 1, 1042077, 0, 0, 0, 0, 0, '', '', '', 'Ashran (PvP)', 'While we are fighting on Draenor, the vile Alliance is trying to recapture the lands of Ashran from us.\r\n\r\nThe fighting spirit of our troops will rise if you take part in the battle and strike terror into the hearts of enemies.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (128, 273, 0, 1041778, 0, 0, 0, 0, 0, '', '', '', 'Mok\'gol Watchtower', 'Songs of War raiders from the Mok\'gol watchtower haunt the entire district. We warn travelers that traveling alone is very dangerous, but not everyone is listening to us.\r\n\r\nIf we attack the Mok\'gol outpost, the War Song clan will go on the defensive, and their raiders will not bother us.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (128, 274, 1, 1042005, 0, 0, 0, 0, 0, '', '', '', 'Pit (group)', 'The forces of the Blackrock clan, based in the Pit area of ​​Gorgrond, form the backbone of the Iron Horde army. If we smash them in their native land, the remnants of the Iron Horde will no longer be able to withstand us.\r\n\r\nIf you decide on this battle, take reliable comrades with you. It’s definitely not worth counting on an easy victory over the Black Mountain clan.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (202, 421, 0, 1126586, 0, 0, 0, 0, 0, '', '', '', 'Sha\'naar Temple', 'In the hills of the Tanaan jungle is an ancient temple. Once it was a holy place, but now the sargerei turned it into their nativity scene - they call demons there.\r\n\r\nWe must strike them before they finish their rituals. The longer we drag with this, the stronger the enemy will be.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (202, 422, 1, 1125250, 0, 0, 0, 0, 0, '', '', '', 'Tron Kiel\'ed', 'The Shadow Council summons its demon lords on the mountain they call the Throne of Kil\'jaeden. Without a doubt, this is the most dangerous region in all of Tanaan.\r\n\r\nSo gather a squad of strong fighters and attack the Throne of Kil\'jaeden, before the Legion has had time to gain a foothold there!\r\n\r\n| cFF7a0000 [Task for the group] | r', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (192, 401, 0, 1125250, 0, 0, 0, 0, 0, '', '', '', 'Iron Fortress Harbor', 'The Iron Horde continues to collect remnants of its forces from all over Draenor. If we allow them to continue to receive reinforcements and supplies without hindrance, our positions in Tanaan will weaken very quickly.\r\n\r\nHaving dealt a strategic blow to their supply routes in the harbor of the Iron Fortress, we will force the enemy to go on the defensive and retain the initiative.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (192, 402, 1, 1125246, 0, 0, 0, 0, 0, '', '', '', 'Fel Forge', 'Gul\'dan\'s minions enhance the Iron Horde war machines with fel magic. Scouts even report on the construction of a felbot!\r\n\r\nFight in the Fel Forge and destroy these infernal machines before there are too many of them.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (204, 425, 0, 1125251, 0, 0, 0, 0, 0, '', '', '', 'Zet\'Gol', 'The Blood-Eye Clan continues to pose a serious threat. In Zet\'Gol, they constantly chase our scouts, interfere with operations and collect resources for Gul\'dan\'s dark magic.\r\n\r\nWe need to organize a raid on Zet\'Gol so that they pull their forces, dispersed throughout the valley, to one point. This will untie our hands at least for a while.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (204, 426, 1, 1125246, 0, 0, 0, 0, 0, '', '', '', 'Fel Forge', 'Gul\'dan\'s minions enhance the Iron Horde war machines with fel magic. Scouts even report on the construction of a felbot!\r\n\r\nFight in the Fel Forge and destroy these infernal machines before there are too many of them.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (253, 541, 0, 1390097, 0, 0, 0, 0, 0, 'Blood', '', '', 'Select', 'Gorelix the Fleshripper is a monstrous demon warrior. With his massive axe, the Maw of the Damned, he has devastated entire worlds on his own.\n\nThe Maw of the Damned allow it\'s bearer to sacrifice their own blood to fuel its dark magic, bolstering the wielder\'s defenses.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (253, 542, 1, 1390098, 0, 0, 0, 0, 0, 'Frost', '', '', 'Select', 'The legendary Frostmourne, even four years after its destruction within Icecrown Citadel, remains one of the most infamous weapons in all of Azeroth.\n\nWith a bit of necromantic power, the broken shards could be reforged into a set of runeblades that have the potential to be as powerful as their predecessor.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (253, 543, 2, 1390099, 0, 0, 0, 0, 0, 'Unholy', '', '', 'Select', 'An ancient blade crafted by the Nathrezim which spreads plague, death and violence in its wake, Apocalypse is a powerful tool of destruction.\n\nThe blade was wielded by the Tirisgarde before it fell in the hands of the Dark Riders. Now the only way to find it is to hunt down the riders to their secret lair.\nApocalypse enhances its owner with powerful shadow magic attacks and fearsome minions.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (242, 511, 0, 1390109, 0, 0, 0, 0, 0, 'Brewmaster', '', '', 'Select', 'Chen Stormstout went off to the Broken Shore and we\'ve not heard back from him.\n\nHis staff is a powerful weapon that was once possessed by the Monkey King, if he fell we can\'t allow the legion to obtain it!', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (242, 512, 1, 1390110, 0, 0, 0, 0, 0, 'Mistweaver', '', '', 'Select', 'Long ago the last pandaren emperor used his staff \"Sheilun\" to shroud all of Pandaria in mists. \n\nThe staff has remained at the Terrace of Eternal Spring for generations. When the Legion attacked Pandaria, Shado-Pan defenders rushed to secure the area. They haven\'t reported back, and we fear the worst - the staff cannot fall into the wrong hands!', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (242, 513, 2, 1390111, 0, 0, 0, 0, 0, 'Windwalker', '', '', 'Select', 'Travelers returning to the isle from abroad have spread an interesting tale. They describe an ancient pair of hand blades that were fabled to grant their bearer the power of the storm.\n\nLittle is known about this mysterious weapon, but if its powers are true then we should consider searching for it.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (248, 532, 0, 1389393, 0, 0, 0, 0, 0, 'Holy', '', '', 'Select', 'The Draenei had to flee from many worlds as the Legion chased after them across the heavens. It is upon one of these worlds where a valiant few remained with the radiant jewel of healing, T\'uure, to face the Legion and allow their friends to escape.\n\nA rumor is spreading that a soldier in Dalaran has seen the lost crystal in possession of the Legion. If this is true it must be retrieved!', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (248, 533, 1, 1389394, 0, 0, 0, 0, 0, 'Shadow', '', '', 'Select', 'An ancient dagger of the Old Gods has resurfaced in a bid to restore the Twilight\'s Hammer to power. They are performing an unholy ritual nearby that must be stopped.\n\nThe Blade of the Black Empire is a powerful void attuned sacrificial dagger that has been used in horrific rites to the Old Gods since time immemorial. It enhances its owners with powerful shadow energy and mental attacks.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (248, 534, 2, 1389392, 0, 0, 0, 0, 0, 'Discipline', '', '', 'Select', 'Obsessed with cleansing undead from Azeroth, the fanatical Scarlet Crusade tried to create a second Ashbringer in the form of a staff. However, due to treachery from within, the ritual failed in a great firey explosion. The damaged staff\'s power proved nearly uncontrollable.\n\nFearing its destructive power, the elite magi of the Kirin Tor hid it away from the hands of men.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (280, 621, 0, 1389396, 0, 0, 0, 0, 0, 'Outlaw', '', '', 'Select', 'The creepy admiral Eliza is a thunderstorm in the South Seas. Her cursed blades scare many.\r\n\r\nWe learned that her ship anchored off the coast of Azsuna on the Broken Isles. If you hurry, you can get her blades.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (280, 622, 1, 1389397, 0, 0, 0, 0, 0, 'Stealth', '', '', 'Select', 'Akaari Blood Darkness is an unsurpassed Eredar assassin, a subject of special pride of the Legion. Her daggers can distort space, hiding its owner in the shade.\r\n\r\nWe have intelligence data indicating where it is currently located. It\'s time to strike.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (270, 594, 0, 1389389, 0, 0, 0, 0, 0, 'Secret magic', '', '', 'Select', 'The most famous owner of Alunet is Aegwynn, the only woman among the Keepers of Tirisfal, although, apparently, the artifact is much older than her.\r\n\r\nWhen her life was drawing to a close, Aegwynne handed the staff to the blue dragons. They found the artifact too dangerous and locked it in a secret vault, where it is to this day.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (270, 595, 1, 1389390, 0, 0, 0, 0, 0, 'Fire', '', '', 'Select', 'Felo\'melorn, in the translation “Blow of Fire”, once glittered in the hands of warriors from the clan of the Solar Wanderers, who valiantly fought in the War of the Ancient and Troll Wars and opposed the death knight Arthas Menethil.\r\n\r\nIn the end, the sword was lost in the icy wastes of Northrend.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (164, 345, 0, 1041776, 0, 0, 0, 0, 0, '', '', '', 'Broken Precipice', 'Massive ogron have been battering our frontlines, and no matter how many we down, there seem to be more to replace them.\n\nMost of these ogron appear to be coming from the Broken Precipice, deep in western Nagrand. If we\'re to stand a chance in the coming battles, we need to find a way to remove these ogron from the battlefield.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (164, 346, 1, 1042005, 0, 0, 0, 0, 0, '', '', '', 'The Pit (Group)', 'The Blackrock forces based out of the Pit in Gorgrond make up the bulk of the Iron Horde army. If we crush them on their home soil, the rest of the Iron Horde will have little hope of standing against us.\n\nIf you choose the battle, bring friends. The Blackrock won\'t be defeated easily.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (284, 633, 0, 1389389, 0, 0, 0, 0, 0, 'Secret magic', '', '', 'Select', 'The most famous owner of Alunet is Aegwynn, the only woman among the Keepers of Tirisfal, although, apparently, the artifact is much older than her.\r\n\r\nWhen her life was drawing to a close, Aegwynne handed the staff to the blue dragons. They found the artifact too dangerous and locked it in a secret vault, where it is to this day.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (284, 635, 1, 1389391, 0, 0, 0, 0, 0, 'Ice', '', '', 'Select', 'This staff belonged to Alodi, the first Guardian of Tirisfal. The staff went through many battles against the Legion with the owner over the century when he wore his honorary title.\r\n\r\nMoving away from business, Alodi disappeared and carried the staff with him. What happened to them later, no one knows - except, perhaps, Alodi himself.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (287, 644, 0, 1389397, 0, 0, 0, 0, 0, 'Stealth', '', '', 'Select', 'Akaari Blood Darkness is an unsurpassed Eredar assassin, a subject of special pride of the Legion. Her daggers can distort space, hiding its owner in the shade.\r\n\r\nWe have intelligence data indicating where it is currently located. It\'s time to strike.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (274, 601, 0, 1389399, 0, 0, 0, 0, 0, 'Improvement', '', '', 'Select', 'Doomhammer sunk into the Maelstrom. Care must be taken that he does not fall into the wrong hands.\r\n\r\nMy husband Go\'el, whom you call Thrall, has already gone to the Underdark to track him down. Beware: Get\'zun’s demon was also dragged into the Maelstrom, and he may still be alive.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (274, 602, 1, 1389398, 0, 0, 0, 0, 0, 'Elements', '', '', 'Select', 'Gladiator Regar is aware of powerful weapons that can help us confront the Legion.\r\n\r\nAfter the Pandaren campaign under the Throne of Thunder, the weapons of the storm god Ra-den were discovered. He was left under the protection of the followers of the White Tiger with the order to give only the most worthy. Regar will help you prove your right to it.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (292, 658, 0, 1389394, 0, 0, 0, 0, 0, 'Darkness', '', '', 'Select', 'The Twilight\'s Hammer cult wants to regain its former power: it conducts a ritual in which the once lost dagger of the Old Gods surfaced. This unholy ritual must be stopped.\r\n\r\nThe blade of the Dark Empire is a dagger for sacrifice, enchanted by the energy of the Abyss. It was used in terrifying rituals dedicated to the Ancient Gods, from time immemorial. The dagger saturates its owner with the powerful energy of darkness.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (273, 599, 0, 1389394, 0, 0, 0, 0, 0, 'Darkness', '', '', 'Select', 'The Twilight\'s Hammer cult wants to regain its former power: it conducts a ritual in which the once lost dagger of the Old Gods surfaced. This unholy ritual must be stopped.\r\n\r\nThe blade of the Dark Empire is a dagger for sacrifice, enchanted by the energy of the Abyss. It was used in terrifying rituals dedicated to the Ancient Gods, from time immemorial. The dagger saturates its owner with the powerful energy of darkness.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (273, 598, 1, 1389393, 0, 0, 0, 0, 0, 'Shine', '', '', 'Select', 'The Draenei had to flee many worlds, fleeing the pursuit of the Legion. In one of these worlds, some of the bravest remained to detain the demons and give the rest time to leave, and they had a shining healing stone - T\'uure.\r\n\r\nRumor has it that in Dalaran a warrior saw a missing crystal in the hands of demons. If true, you need to get it.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (273, 600, 2, 1389392, 0, 0, 0, 0, 0, 'Obedience', '', '', 'Select', 'The scarlet order, obsessed with the idea of ​​cleansing Azeroth from the undead, tried to create a staff - the likeness of the Incinerator. However, a scout from the Legion, who entered the order, intervened in the creation ritual - and it all ended in a powerful fiery explosion. The strength of the damaged staff was almost impossible to control.\r\n\r\nFearing destruction and chaos, the high magicians of the Kirin Tor hid the staff where no one could find it.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (279, 617, 0, 1389401, 0, 0, 0, 0, 0, 'Witchcraft', '', '', 'Select', 'The reaper of the Dead Wind once belonged to the first of the necrolytes, Satael, and at one time destroyed all life on the pass of the Dead Wind. For many centuries, he was lost sight of, but recently it turned out that Ulthales is in the hands of the Dark Riders. You need to track them down to find out where they hid the artifact.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (279, 618, 1, 1389402, 0, 0, 0, 0, 0, 'Demonology', '', '', 'Select', 'Sorcerer Tal\'kiel was one of the first eredars to master the technique of summoning and controlling demons.\r\nWhen he was defeated, his skull was put on public display as a reminder of how dangerous dark art is.\r\nBut this lesson has not been learned.\r\n\r\nAfter the fall of the Eredar, the commanders of the Burning Legion took the skull to strengthen control over their troops.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (282, 626, 0, 1390102, 0, 0, 0, 0, 0, 'Balance', '', '', 'Select', 'The spit of Elune, kept by Tyrande, the High Priestess of Elune, is known among the Druids for its long and controversial history.\r\n\r\nThe artifact is associated with the origin of the worgen and, as they say, has an unimaginable lunar power, which only the most skilled of the druids can curb.\r\n\r\nWe need to convince Tyrande and her people that the Scythe can be trusted with you.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (282, 628, 1, 1390104, 0, 0, 0, 0, 0, 'Watchman', '', '', 'Select', 'The mighty bear god Ursoc died during the War of the Ancients, protecting Azeroth from the Burning Legion.\r\n\r\nHis claws, once terrifying enemies, are now kept in the Emerald Dream, and the spirit of Ursoc protects them.\r\n\r\nIf you can get the Claws, they will greatly help us in the fight against the Legion.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (282, 629, 2, 1390105, 0, 0, 0, 0, 0, 'Healing', '', '', 'Select', 'Many thousands of years ago, Aviana presented the first druids with a branch of G\'Hanir, the Primordial Tree.\r\n\r\nThe branch has become a staff that is said to help its owner achieve perfect harmony with nature and learn very powerful healing spells.\r\n\r\nThe artifact is stored in the sanctuary under the roots of Chaladrassil, but not so long ago, communication with the local druids was lost.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (275, 605, 0, 1389406, 0, 0, 0, 0, 0, 'Protection', '', '', 'Select', 'Once, the ancient king of vrykul managed to get the scales of the Earth Keeper Neltharion and make of it a shield of unprecedented power. This shield now rests next to its creator in a forgotten tomb.\r\n\r\nGet this shield and you will get not only impenetrable protection, but also a particle of fiery power of one of the Aspects.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (275, 606, 1, 1389405, 0, 0, 0, 0, 0, 'Fury', '', '', 'Select', 'The battle swords of the Valariars, the greatest of my defenders, were stolen by this damned Helia. She and her foolish servant taunt the heroes, abducting their souls before they can ascend to the Halls of Valor.\r\n\r\nWith this powerful weapon in battle, you will become like a storm of steel and fire. Better and can not be desired.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (277, 610, 0, 1390109, 0, 0, 0, 0, 0, 'Khmelevar', '', '', 'Select', 'Legends tell of a staff that was made of the first tree grown on the land of Pandaria.\r\n\r\nThe one who owns this staff, as if he could not hit a single weapon.\r\n\r\nThe last known owner was the Monkey King. With him we should begin the search.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (277, 611, 1, 1390110, 0, 0, 0, 0, 0, 'Weaver of fog', '', '', 'Select', 'Once upon a time, the last Pandaren emperor with the help of Shey-moon, his staff, covered the whole country with fogs.\r\n\r\nFor many generations the staff was kept on the Terrace of Eternal Spring. When the Legion attacked Pandaria, the Shado-Pan defenders rushed there. Since then there has been no news from them, and we fear the worst. The staff should not go to the enemy!', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (288, 645, 0, 1390100, 0, 0, 0, 0, 0, 'Extermination', '', '', 'Select', 'These twin blades belong to the former demon hunter Varedis the Corrupted Soul, who died many years ago defending the Black Temple.\r\n\r\nLord of the Burning Legion Kil\'jaeden the Tempter returned Varedis from the Twisting Nether and filled his glaives with his chaotic power.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (274, 603, 2, 1389400, 0, 0, 0, 0, 0, 'Healing', '', '', 'Select', 'It is said that Queen Azshara had a scepter that allowed her to command the seas and waters of life.\r\n\r\nErunak had long tried to find out his whereabouts, and one of his shamans almost succeeded, but she disappeared. Did her searches succeed? Can legends turn out to be true? And what can this artifact be capable of in the hands of a talented shaman?', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (245, 523, 2, 1389401, 0, 0, 0, 0, 0, 'Affliction', '', '', 'Select', 'Wielded by Sataiel, the first necrolyte, the Deadwind Harvester earned its name by stripping the life from the lands known as Deadwind pass.\n\nAfter centuries locked away, Ulthalesh has been discovered in the posession of the Dark Riders. You must hunt them down if you wish to find where they have it hidden.', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (237, 495, 0, 841057, 0, 0, 0, 0, 0, '', '', '', 'Here is my choice.', 'Choose this option if you want to learn how to cut |cFF1EFF00|Hitem130216:0:0:0:0:0:0:0:90:0|h[boost speed]|h|r,which increases your speed indicator.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (237, 494, 1, 841057, 0, 0, 0, 0, 0, '', '', '', 'Here is my choice.', 'Choose this option if you want to learn how to cut |cFF1EFF00|Hitem:130215:0:0:0:0:0:0:0:90:0|h[deadly dark amber]|h|r, which increases your critical strike damage .', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (237, 496, 2, 841057, 0, 0, 0, 0, 0, '', '', '', 'Here is my choice.', 'Choose this option if you want to learn how to cut |cFF1EFF00|Hitem:130218:0:0:0:0:0:0:0:90:0|h[deadly dark amber]|h|r, which increases your skill.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (238, 498, 0, 841057, 0, 0, 0, 0, 0, '', '', '', 'Here is my choice.', 'Choose this option if you want to learn how to create |cFF0070DD|Hitem:130223:0:0:0:0:0:0:0:90:0|h[dark amber ring]|h|r, which increases your critical strike .', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (238, 499, 1, 841057, 0, 0, 0, 0, 0, '', '', '', 'Here is my choice.', 'Choose this option if you want to learn how to create |cFF0070DD|Hitem:130225:0:0:0:0:0:0:0:90:0|h[azsunite ring]|h|r, which increases your speed indicator.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (238, 497, 2, 841057, 0, 0, 0, 0, 0, '', '', '', 'Here is my choice.', 'Choose this option if you want to learn how to create |cFF0070DD|Hitem:130224:0:0:0:0:0:0:0:90:0|h[a ring with a heavenly stone]|h|r, which increases your universality index.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (246, 527, 0, 841057, 0, 0, 0, 0, 0, '', '', '', 'Here is my choice.', 'Choose this option if you want to learn how to create |cFF0070DD|Hitem:130220:0:0:0:0:0:0:0:90:0|h[fast light]|h|r, which increases your speed indicator.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (246, 526, 1, 841057, 0, 0, 0, 0, 0, '', '', '', 'Here is my choice.', 'Choose this option if you want to learn how to create |cFF0070DD|Hitem:130219:0:0:0:0:0:0:0:90:0|h[the deadly eye of the Prophecy]|h|r, which increases your critical strike damage .', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (246, 528, 2, 841057, 0, 0, 0, 0, 0, '', '', '', 'Here is my choice.', 'Choose this option if you want to learn how to create |cFF0070DD|Hitem:130220:0:0:0:0:0:0:0:90:0|h[dark mastery ruby]|h|r, which increases your skill indicator.', '', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (247, 545, 3, 1390105, 0, 0, 0, 0, 0, 'Restoration', '', '', 'Select', 'Thousands of years ago, Aviana gifted the first druids a branch from the Mother Tree, G\'Hanir.\n\nIt is said that the staff aids its wielder in achieving perfect harmony with nature, allowing them to tap into deeply powerful restorative spells.\n\nThe branch is kept at a shrine beneath the roots of Shaladrassil, but contact has recently been lost with the druids there...', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (240, 504, 2, 1390106, 0, 0, 0, 0, 0, 'Beast Mastery', '', '', 'Select', 'In ancient times, a vrykul warlord stole a rifle infused with the power of storms. He used the artifact\'s might to conquer his rivals on the Broken Isles.\n\nDelve into the warlord\'s tomb and recover this mighty weapon!', 'CONFIRM_ARTIFACT_CHOICE', NULL, 27062);
INSERT INTO `playerchoice_response` VALUES (87, 192, 0, 1041980, 0, 0, 0, 0, 0, '', '', '', 'Shattrath (group)', 'Every day, the Sargerai troops in Shattrath are becoming stronger and bolder. They pose a serious threat and can no longer be ignored.\r\n\r\nGather allies if you want to launch an attack on the Sargerais who took refuge in the city.', '', NULL, 26365);
INSERT INTO `playerchoice_response` VALUES (87, 191, 0, 1042067, 0, 0, 0, 0, 0, '', '', '', 'Plateau of the Secretary', 'Recent reports indicate increased activity of the Sargerai troops on the Socretar Plateau in the Shadowmoon Valley.\r\n\r\nSocrethar\'s minions present a danger to both the draenei and our garrison. You need to deal with them as soon as possible.', '', NULL, 26365);
INSERT INTO `playerchoice_response` VALUES (352, 997, 0, 1851141, 0, 0, 0, 0, 0, 'Gorgrond', '', '', 'Go to Gorgrond', 'The Blackrock Orcs are great masters in working with Blackrock ore, from which they smelter guns for the artillery and fleet of the Iron Horde.\r\n\r\nSet up a base in Gorgrond and stop the Iron Horde\'s mechanical battalion, terrifying Draenor.', '', NULL, 26365);
INSERT INTO `playerchoice_response` VALUES (308, 753, 0, 1854486, 0, 0, 0, 0, 0, 'Nightborne Elves', '', '', 'Select', 'After thousands of years of isolation, the night-born Suramar want to find their place in the world again. Lady Liadrin believes that the Horde will benefit from an alliance with these ancient elves.', 'CONFIRM_ALLY_CHOICE', NULL, 26654);
INSERT INTO `playerchoice_response` VALUES (308, 752, 0, 1854484, 0, 0, 0, 0, 0, 'Highmountain Tauren', '', '', 'Select', 'Highmountain Tauren have teamed up to push the Burning Legion from their lands. Bane Bloodhoof believes that they will serve the Horde well because of their strength and generosity.', 'CONFIRM_ALLY_CHOICE', NULL, 26654);
INSERT INTO `playerchoice_response` VALUES (322, 783, 0, 1854487, 0, 0, 0, 0, 0, 'Void Elves', '', '', 'Select', 'Alleria Windrunner learned of a group of blood elves exiled for studying Void magic. He believes that if you find these apostates, you can attract them to the Alliance.', 'CONFIRM_ALLY_CHOICE', NULL, 26755);
INSERT INTO `playerchoice_response` VALUES (322, 784, 0, 1854485, 0, 0, 0, 0, 0, 'Illuminated Draenei', '', '', 'Select', 'The Army of the Light played a key role in defeating the Burning Legion on Argus. High Exarch Turalyon believes that the Illuminators will proudly defend the Alliance from enemy attacks.', 'CONFIRM_ALLY_CHOICE', NULL, 26822);
INSERT INTO `playerchoice_response` VALUES (317, 776, 0, 1707689, 0, 0, 0, 0, 0, 'Shroud of Echoes', '', '', 'Select', 'Selecting this allows use of the Shroud of Arcane Echoes\' invisibility power while on Argus.', '', NULL, 27602);
INSERT INTO `playerchoice_response` VALUES (317, 775, 0, 1707686, 0, 0, 0, 0, 0, 'Desecrated Heart', '', '', 'Select', 'By choosing the defiled heart of Argus, you will be able to heal outside the battle, as well as return to life after taking mortal damage.', '', NULL, 27602);
INSERT INTO `playerchoice_response` VALUES (317, 771, 0, 1707688, 0, 0, 0, 0, 0, 'Justice of the Light', '', '', 'Select', 'By choosing this ability, you can specify the targets for the shelling from the \"Justice of the Light\", the main weapon of the \"Vindicar\". Valid only on Argus.', '', NULL, 27602);
INSERT INTO `playerchoice_response` VALUES (317, 782, 0, 1707688, 0, 0, 0, 0, 0, '', '', '', 'Activate', 'Activate the core of the matrix and select \"Justice of the Light\" - the main tool of \"Vindicar\" - as the ability to use on Argus.', '', NULL, 27602);
INSERT INTO `playerchoice_response` VALUES (317, 774, 0, 1707687, 0, 0, 0, 0, 0, 'Warframe', '', '', 'Select', 'Selecting this allows use of the Lightforged Warframe mechanized armor suit while on Argus.', '', NULL, 27602);
INSERT INTO `playerchoice_response` VALUES (70, 158, 0, 1042005, 0, 0, 0, 0, 0, '', '', '', 'Pit (group)', 'The forces of the Blackrock clan, based in the Pit area of ​​Gorgrond, form the backbone of the Iron Horde army. If we smash them in their native land, the remnants of the Iron Horde will no longer be able to withstand us.\r\n\r\nIf you decide on this battle, take reliable comrades with you. It’s definitely not worth counting on an easy victory over the Black Mountain clan.', '', NULL, 25961);
INSERT INTO `playerchoice_response` VALUES (70, 157, 0, 1042067, 0, 0, 0, 0, 0, '', '', '', 'Plateau of the Secretary', 'Recent reports indicate increased activity of the Sargerai troops on the Socretar Plateau in the Shadowmoon Valley.\r\n\r\nSocrethar\'s minions present a danger to both the draenei and our garrison. You need to deal with them as soon as possible.', '', NULL, 25961);
INSERT INTO `playerchoice_response` VALUES (509, 0, 1, -2071656704, 3687857, 1629516361, 0, 0, 32, 'e Arathi cerca.La Horda controla Ar\'gorok y las Tierras Altas de Arathi. Los espías mortacechadores informan que la Alianza está organizando su propia campaña de guerra en Arathi.�6%)Ҭ��B(Ir a la batallaLa batalla por Costa OscuraAsedioRecompensa por ganar:Lucha junto a tus aliados para expulsar a la Alia', 'nza de Costa Oscura.Frentes de batalla', '', 'llaBatalla por StromgardePatrullar¡Derrota monstruos poco comunes y fuerzas enemigas en las Tierras Altas de Arathi por la posibilidad de obtener recompensas especiales! Se ha abierto un portal a las Tierras Altas d', '', '', 0, 29297);
INSERT INTO `playerchoice_response` VALUES (509, 1445, 0, 2143999, 1, 0, 0, 0, 154, '', '', '', '', '', '', 0, 29297);
INSERT INTO `playerchoice_response` VALUES (535, 118529, 1, 8449, 6292992, 1919905857, 0, 0, 116, ' de infligir una gran cantidad de daño a las defensas enemigas.��&�$�`Aportar |cFFFF202010|TINTERFACE\\ICONS\\INV_TRADESKILLITEM_01.BLP:15:15:5|tContribuye a la construcción de Talleres de la Peste.\n\nOtorga acceso a los Lanzañublos renegados, vehículos de asedio poderosos capaces de infligir una gran cantidad de daño a las defensas enemigas.Construir Talleres de la Peste', '', '', 'FF202010|TINTERFACE\\ICONS\\INV_INGOT_IRON.BLP:15:15:5|tContribuye a la construcción de Talleres de la Peste.\n\nOtorga acceso a los Lanzañublos renegados, vehículos de asedio poderosos capaces', '', '', 0, 29297);
INSERT INTO `playerchoice_response` VALUES (535, 1716, 0, 2532101, 3, 0, 0, 0, 144, '', '', '', '', '', '', 0, 29297);
INSERT INTO `playerchoice_response` VALUES (535, 1715, 0, 2532101, 0, 0, 0, 0, 144, '', '', '', '', '', '', 0, 29297);
INSERT INTO `playerchoice_response` VALUES (533, 118529, 1, 8449, 14156288, 1919905857, 0, 0, 116, 'FFFFF10|TINTERFACE\\ICONS\\INV_TRADESKILLITEM_01.BLP:15:15:5|tContribuye a la construcción del Bastión.\n\nAumenta la velocidad de entrega de recursos.Construir Bastión', '', '', 'FF202010|TINTERFACE\\ICONS\\INV_INGOT_IRON.BLP:15:15:5|tContribuye a la construcción del Bastión.\n\nAumenta la velocidad de entrega de recursos.��&�$��Aportar |cFFF', '', '', 0, 29297);
INSERT INTO `playerchoice_response` VALUES (533, 1704, 0, 2532100, 3, 0, 0, 0, 138, '', '', '', '', '', '', 0, 29297);
INSERT INTO `playerchoice_response` VALUES (537, 118529, 1, 8449, 1573888, 1919905857, 0, 0, 116, '�$�Aportar |cFFFFFFFF10|TINTERFACE\\ICONS\\INV_TRADESKILLITEM_01.BLP:15:15:5|tContribuye a la construcción de la Armería.\n\nOtorga acceso a investigaciones que aumentan el poder y la defensa de los aliados.Construir Armería', '', '', 'FF202010|TINTERFACE\\ICONS\\INV_INGOT_IRON.BLP:15:15:5|tContribuye a la construcción de la Armería.\n\nOtorga acceso a investigaciones que aumentan el poder y la defensa de los aliados.��&', '', '', 0, 29297);
INSERT INTO `playerchoice_response` VALUES (537, 1728, 0, 2532098, 3, 0, 0, 0, 132, '', '', '', '', '', '', 0, 29297);
INSERT INTO `playerchoice_response` VALUES (529, 1670, 0, 2532103, 3, 0, 0, 0, 0, '', '', '', '', '', '', 0, 29297);
INSERT INTO `playerchoice_response` VALUES (537, 1727, 0, 2532098, 0, 0, 0, 0, 132, '', '', '', '', '', '', 0, 29297);

SET FOREIGN_KEY_CHECKS = 1;
